#!/bin/bash

SRC="main.sg"

build() {
  mix compile >/dev/null
  mix execute $SRC
}

check() {
  mix check --no-retry
}

docs() {
  mix docs --open
}

repl() {
  mix compile >/dev/null
  rlwrap mix repl
}

publish() {
  mix docs
  lift deploy
}

release() {
  mix hex.publish
}
