#!/bin/bash

SRC="main.sg"
DOC="doc"

# build() {
#   mix compile >/dev/null
#   mix execute $SRC
# }

build() {
  rm -rf _build/out.S
  mix run -e "Signo.main()" > _build/out.S
  nasm -f macho64 _build/out.S -o _build/out.o
  ld -arch x86_64 _build/out.o -o _build/out -platform_version macos 13.0 14.5
  arch -x86_64 _build/out
  echo $?
}

check() {
  mix check --no-retry
}

docs() {
  mix docs && open $DOC/index.html
}

repl() {
  mix compile >/dev/null
  rlwrap mix repl
}

# Temporary

publish() {
  mix docs || exit 1
  trap p:post_publish EXIT
  mv $DOC signo
  scp -r signo du11:public_ftp/
  p:post_publish
}

p:post_publish() {
  rm -rf signo
}
