#!/bin/bash

build() {
  mix compile >/dev/null
  mix run -e "Signo.main()"
}

check() {
  mix check --no-retry
}

docs() {
  mix docs && open doc/index.html
}

repl() {
  mix compile >/dev/null
  mix run -e "Signo.repl()"
}